# Launch [Builds, (re)creates, starts] using $ docker compose
#
# Custom ROS2/Ubuntu Docker Image&Container for RaspberryPI(arm64v8 CPU Architecture)
#  - Enabling hardware access like I2C, GPIO and SPI.
#
# Prerequisite - On docker host: 
#   I) Raspberry Pi(arm64v8) with Ubuntu & Docker installed.
#  II) Enable x11 gui from inside the Docker Image/Container.
#       $ xhost local:docker
#----------------------
# Commands:
#  1) Build Image + Create and Start Container in the background.
#     $ docker compose up --detach --build 
#             or
#     $ docker compose up --detach
#
#  2) List running/active/paused containers
#     $ docker compose ps -all
#
#  3)  Connect bash/terminal to existing/new container: 
#      $ docker exec -it pet-base-jazzy_container bash
#----------------------
# Maintainer: stefan.kull@gmail.com
# License: MIT
# https://github.com/Pet-Series
#
#  - ROS2 version: ROS2/jazzy(arm64v8)
#  - OS version:   Ubuntu 24.04/noble(arm64v8)
#
# More info: 
#  - https://github.com/Pet-Series/pet_docker
#  - https://hub.docker.com/repositories/kullken
#  - https://hub.docker.com/repository/docker/kullken/ros2_arm64v8
#  - https://hub.docker.com/r/arm64v8/ros/tags?page=1&name=jazzy

services:
  ros2:
    build: .
    image: kullken/ros2_arm64v8:pet-base-jazzy
    container_name: pet-base-jazzy_container
    labels:
      - "se.pet-series.description=ROS2 Stuff for Pet-Series[service]"
    deploy:
      labels:
      - "se.pet-series.description=ROS2 Stuff for Pet-Series[deploy]"
    environment:
      - DISPLAY=${DISPLAY}
      - HOSTUSER=${USER} 
    privileged: true
    network_mode: host
    devices:
      #- "/dev/ttyUSB0:/dev/ttyUSB0"     # USB
      - /dev/gpiomem:/dev/gpiomem:rw     # GPIO memory mapping
      - /dev/i2c-1:/dev/i2c-1:rw         # I2C-1
      #- "/dev/i2c-2:/dev/i2c-2"         # I2C-2
      - /dev/spidev0.0:/dev/spidev0.0:rw # SPI.0
      - /dev/spidev0.1:/dev/spidev0.1:rw # SPI.1
      - /dev/vchiq:/dev/vchiq:ro         # CPU/Broadcom-core stuff...

    volumes:
      - /home/pi/ws_ros2:/home/pet/ws_ros2:rw   # Shared developing/source code folder.
      - /etc/localtime:/etc/localtime:ro        # Sync docker image/container date & timezone with docker-host
      - /proc/device-tree:/proc/device-tree:ro  # Broadcom/CPU-core stuff...
     # - /lib:/lib:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro  # Broadcom/CPU-core stuff...
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # restart: always
    # restart: unless-stopped
    command: 
      - /bin/bash