# ROS2 test/tutorial - Run the ROS2 demo_node 'talker' and 'listener'
#
# I  Pull down Docker Image.
#    Create and run two Docker services with eatch new/created Docker Container.
#    - Docker Container 1 'amd64-jazzy-talker-1'
#    - Docker Container 2 'amd64-jazzy-listener-1'
#    - Docker Network      amd64-jazzy_default 
# II In eatch Docker Services/Container - Launch Command ROS2 demo_node 'talker' and 'listener'
#
# 1) Launch the nodes
#    $ docker compose --file docker-compose_ROS2talker-listener.yml up
#    ... ✔ Container1                                                                                                                                                                                          0.0s 
#    ... ✔ Container2 
#   
# 2) ...press <Ctrl><C> to stop the two Docker Services/Container.
#
# 3) Remove the two Docker Containers AND the Docker Network "amd64-jazzy_default"
#    $ docker compose --file docker-compose_ROS2talker-listener.yml down
#
#----------------------
# Maintainer: stefan.kull@gmail.com
# Licens: MIT
# https://github.com/Pet-Series
#----------------------
# More info: https://github.com/Pet-Series/pet_docker
# More info: https://hub.docker.com/repositories/kullken
# More info: https://docs.ros.org/en/jazzy/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.html
# More info: https://hub.docker.com/_/ros
services: 
  talker: 
    image: osrf/ros:jazzy-desktop
    command: ros2 run demo_nodes_cpp talker 
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  listener: 
    image: osrf/ros:jazzy-desktop 
    command: ros2 run demo_nodes_cpp listener
    depends_on: 
      - talker 
    stdin_open: true # docker run -i
    tty: true        # docker run -t