# ROS2 test/tutorial - Pull down/Run/Launch two nodes in two separate docker containers.
# Using the built in ros2 package 'demo_nodes_cpp' with the two nodes 'talker' & 'listener'
#
# 1) Launch the nodes
#    $ docker compose up
#   
# 2) ...press <Ctrl><C> to stop
#
# More info: https://docs.ros.org/en/jazzy/How-To-Guides/Run-2-nodes-in-single-or-separate-docker-containers.html
#
services: 
  talker: 
    image: osrf/ros:jazzy-desktop 
    command: ros2 run demo_nodes_cpp talker 

  listener: 
    image: osrf/ros:jazzy-desktop 
    command: ros2 run demo_nodes_cpp listener
    depends_on: 
      - talker 