# Launch a plain Ubuntu Noble 24.04
#
# 1) Launch the node
#    $ docker compose --file docker-compose_noble.yml up --detach
#
# 2)  Connect bash to existing/new container: 
#     $ docker exec -it ubuntu-nobel-container bash
#
services: 
  bash: 
    image: ubuntu:noble
    container_name: ubuntu-nobel-container
    network_mode: host
    environment:
      # Pass truth the $DISPLAY value to the container - Enable docker GUI-applications to access docker-host xhost screen. 
      - DISPLAY=${DISPLAY}
    volumes:
      # Sync docker date, timezone with docker-host 
      - /etc/localtime:/etc/localtime:ro
      # Enable docker GUI-applications to access docker-host xhost screen.  
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true # docker run -i
    tty: true        # docker run -t