# Launch [Builds Image, (re)creates & starts Container] using $ docker compose
# - Based on Dockerfile in current directory = '/home/sk/ws_ros2/src/pet_docker/pet-mk-viii-runtime-humble'
#
# Prerequisite - On docker host: 
#       I)  That '$ xhost local:docker' is started before the container is started. To enable GUI/X11 applications inside the container
#       II) Docker host must clone https://github.com/Pet-Series/Pet-Mk-VIII.git => /home/pet/ws_ros2/src
#----------------------
# Commands:
#  1) Build Image + Create and Start Container in the background.
#     $ docker compose up --detach --build 
#             or
#     $ docker compose up --detach
#
#  2) List running/active/paused containers
#     $ docker compose ps -all
#
#  3)  Connect bash/terminal to existing/new container:
#      $ ./docker_exec.sh
#             or
#      $ docker exec -it pet-mk-viii-humble_container bash
#----------------------
# Maintainer: stefan.kull@gmail.com
# License: MIT
# https://github.com/Pet-Series
#
#  - ROS2 version: ROS2/humble(arm64v8)
#  - OS version:   Ubuntu 22.04/jammy(arm64v8)
#
# More info: 
#  - https://github.com/Pet-Series/pet_docker
#  - https://hub.docker.com/repositories/kullken
#  - https://hub.docker.com/repository/docker/kullken/ros2_arm64v8
#  - https://hub.docker.com/r/arm64v8/ros/tags?page=1&name=humble

services:
  ros2:
    build: .
    image: kullken/ros2_arm64v8:pet-mk-viii-humble
    container_name: pet-mk-viii-humble_container
    labels:
      - "se.pet-series.description=ROS2 Humble for Pet-Mk.VIII (aka.'Dashboard')"
    privileged: true
    network_mode: host
    devices:
      #- "/dev/ttyUSB0:/dev/ttyUSB0"     # USB
      - /dev/gpiomem:/dev/gpiomem:rw     # GPIO memory mapping
      - /dev/i2c-1:/dev/i2c-1:rw         # I2C-1
      #- "/dev/i2c-2:/dev/i2c-2"         # I2C-2
      - /dev/spidev0.0:/dev/spidev0.0:rw # SPI.0
      - /dev/spidev0.1:/dev/spidev0.1:rw # SPI.1
      - /dev/vchiq:/dev/vchiq:ro         # Broadcom/CPU-core stuff...
    volumes:
      - /home/pi/ws_ros2:/home/pet/ws_ros2:rw   # Shared developing/source code folder.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw        # Enable GUI/X11
      - /etc/localtime:/etc/localtime:ro        # Sync docker image/container date & timezone with docker-host
      - /proc/device-tree:/proc/device-tree:ro  # Broadcom/CPU-core stuff...
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro  # Broadcom/CPU- graphic stuff...
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # restart: always
    # restart: unless-stopped
    # command: [ "ros2", "launch", "pet_mk_viii", "pet-mk-viii-bringup.launch.py"]
    # command: 
    #  - /bin/bash
    # entrypoint: ["/home/pet/ros_entrypoint.sh"]