# Launch [Builds, (re)creates, starts] using $ docker compose
#
# Custom ROS2/Ubuntu Docker Image&Container for RaspberryPI(arm64v8 CPU Architecture)
#  - Enabling hardware access like I2C, GPIO and SPI.
#
# Prerequisite - On docker host: 
#   I) Raspberry Pi(arm64v8) with Ubuntu & Docker installed.
#  II) Before start Image/Container: Enable x11/gui to be used from inside the Docker Image/Container.
#      Make sure that '$ xhost local:docker' is started before the container is started.
#       $ xhost local:docker
# III) Clone https://github.com/Pet-Series/Pet-Mk-VIII.git => To Docker host file system dir. '/home/pet/ws_ros2-jazzy/src'
#----------------------
# Commands:
#  1) Build Image + Create and Start Container in the background.
#     $ docker compose up --detach --build 
#             or
#     $ docker compose up --detach
#
#  2) List running/active/paused containers
#     $ docker compose ps -all
#
#  3)  Connect bash/terminal to existing/new container:
#      $ ./docker_exec.sh
#             or
#      $ docker exec -it pet-mk-viii-jazzy_container bash
#----------------------
# Maintainer: stefan.kull@gmail.com
# License: MIT
# https://github.com/Pet-Series
#
#  - ROS2 version: ROS2/jazzy(arm64v8)
#  - OS version:   Ubuntu 24.04/noble(arm64v8)
#
# More info: 
#  - https://github.com/Pet-Series/pet_docker
#  - https://hub.docker.com/repositories/kullken
#  - https://hub.docker.com/repository/docker/kullken/ros2_arm64v8
#  - https://hub.docker.com/r/arm64v8/ros/tags?page=1&name=jazzy
services:
  ros2:
    build: .
    image: kullken/ros2_arm64v8:pet-mk-viii-jazzy
    container_name: pet-mk-viii-jazzy_container
    labels:
      - "se.pet-series.description=ROS2 jazzy for Pet-Mk.VIII (aka.'Dashboard')"
    privileged: true
    network_mode: host
    devices:
      #- /dev/ttyUSB0:rw    # USB
      - /dev/gpiomem:rw     # GPIO memory mapping
      - /dev/i2c-1:rw       # I2C-1
      #- /dev/i2c-2:rw      # I2C-2
      - /dev/spidev0.0:rw   # SPI.0
      - /dev/spidev0.1:rw   # SPI.1
      - /dev/vchiq:ro       # Broadcom/CPU-core stuff...
    volumes:
      - /home/pi/ws_ros2:/home/pet/ws_ros2:rw   # Shared developing/source code folder.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw        # Enable GUI/X11
      - /etc/localtime:/etc/localtime:ro        # Sync docker image/container date & timezone with docker-host
      - /proc/device-tree:/proc/device-tree:ro  # Broadcom/CPU-core stuff...
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro  # Broadcom/CPU-graphic stuff...
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # restart: always
    # restart: unless-stopped
    # command: [ "ros2", "launch", "pet_mk_viii", "pet-mk-viii-bringup.launch.py"]
    # command: 
    #  - /bin/bash