# Launch [Builds Image, (re)creates & starts Container] using $ docker compose
# - Based on Dockerfile in current directory = '/home/sk/ws_ros2/src/pet_docker/pet-mk-viii-runtime-humble'
#
# Prerequisite - On docker host: 
#       I)  That '$ xhost local:docker' is started before the container is started. To enable GUI/X11 applications inside the container
#       II) Docker host must clone https://github.com/Pet-Series/Pet-Mk-VIII.git => /home/pet/ws_ros2/src
#----------------------
# Launch with: 
# $ docker compose up -d

# Connect shell/bash by: 
# $ docker exec -it pet-mk-viii-runtime_container bash
#----------------------
# Maintainer: stefan.kull@gmail.com
# Licens: MIT
# https://github.com/Pet-Series
#
# "humble"= ROS2
# "focal"  = Ubuntu 20.04 
#
# More info: 
#    - https://github.com/Pet-Series/pet_docker
#    - https://hub.docker.com/repositories/kullken
#    - https://hub.docker.com/repository/docker/kullken/ros2_arm64v8
#    - https://hub.docker.com/r/arm64v8/ros/tags?page=1&name=humble
version: "3"
services:
  ros2:
    image: kullken/ros2_arm64v8:pet-mk-v-runtime
    container_name: pet-mk-viii-runtime_container
    # privileged: true
    devices:
    #- "/dev/ttyUSB0:/dev/ttyUSB0"     # USB
    - "/dev/gpiomem:/dev/gpiomem"     # GPIO
    - "/dev/i2c-1:/dev/i2c-1"         # I2C-1
    #- "/dev/i2c-2:/dev/i2c-2"         # I2C-2
    - "/dev/spidev0.0:/dev/spidev0.0" # SPI.0
    - "/dev/spidev0.1:/dev/spidev0.1" # SPI.1
    network_mode: "host"
    #networks:
    #- hostnet
    volumes:
    - /home/pi/ws_ros2:/home/pet/ws_ros2:rw
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # restart: always
    # restart: unless-stopped
    command: [ "ros2", "launch", "pet_mk_viii", "pet-mk-viii-bringup.launch.py"]

# networks:
#   hostnet:
#     external: true
#     name: host    