# Launch [Builds, (re)creates, starts] using $ docker compose
# - ./Dockerfile in current directory = '/home/${USER}/ws_ros2/src/pet_docker/pet-base-galactic'
#
# Prerequisite - On docker host: 
#       I) That '$ xhost local:docker' is started before the container is started. To enable GUI/X11 applications in the container
#----------------------
# Commands:
#   1)  Enable X11 from inside the Docker Image/Container
#       $ xhost local:docker
#
#   2a) Create/Start Container from Image : 
#       $ docker compose up --detach --build
#   2b) List running/active/paused
#       $ docker compose ps -all
#
#   3)  Connect bash to existing/new container: 
#       $ docker exec -it pet-base-galactic_container bash
#          OR
#       $ ./docker_exec.sh
#
#   4)  Stop, or remove, your container once you've finished with them.
#       $ docker conpose pause / unpause
#       $ docker compose stop / start
#       $ docker compose down    (stop & remove container)
#       $ docker container kill pet-mk-iv-simulation_container
#       $ docker container prune
#----------------------
# Maintainer: stefan.kull@gmail.com
# Licens: MIT
# https://github.com/Pet-Series
#
# "galactic" = ROS2
# "focal"  = Ubuntu 20.04 
#
# More info: 
#    - https://github.com/Pet-Series/pet_docker
#    - https://hub.docker.com/repositories/kullken
#    - https://hub.docker.com/repository/docker/kullken/ros2_arm64v8
#    - https://hub.docker.com/r/arm64v8/ros/tags?page=1&name=galactic
services:
  ros2:
    build: .
    image: kullken/ros2_arm64v8:pet-base-galactic
    container_name: pet-base-galactic_container
    labels:
      - "se.pet-series.description=ROS2 Galatic Pet-series(label)"
    environment:
      - DISPLAY=${DISPLAY}
      - HOSTUSER=${USER} 
    privileged: true
    devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0    # USB
      - /dev/gpiomem:/dev/gpiomem     # GPIO
      - /dev/i2c-1:/dev/i2c-1         # I2C-1
      #- /dev/i2c-2:/dev/i2c-2        # I2C-2
      - /dev/spidev0.0:/dev/spidev0.0 # SPI.0
      - /dev/spidev0.1:/dev/spidev0.1 # SPI.1
      - /dev/video0:/dev/video0       # USB/Web camera
    network_mode: host
    volumes:
      - /home/pi/ws_ros2-galactic:/home/pet/ws_ros2-galactic:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # Enable X11
      - /etc/localtime:/etc/localtime:ro   # Sync timezone
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # restart: always
    # restart: unless-stopped
    # command: [...stuff...]  